// src/lib/month/MonthTableContainer.svelte
<script lang="ts">
	import type { Category, NewBudget } from '../../types';
	import { saveBudget } from '$lib/services/budgetService';
	import MonthTable from './MonthTable.svelte';
	import BudgetForm from './BudgetForm.svelte';
	import Card from '$lib/components/Card.svelte';
	import Modal from '$lib/components/Modal.svelte';
	import { budgets, categories, transactions } from '$lib/stores';

	export let selectedCategory: Category;
	export let selectCategory: (category: Category) => void;

	let isBudgetDialogOpen = false;

	const setBudget = () => isBudgetDialogOpen = true;

	async function handleBudget(budget: NewBudget) {
		isBudgetDialogOpen = false;
		const savedBudget = await saveBudget(budget);

		const newBudgets = $budgets;
		newBudgets[savedBudget.categoryId.toString()] = savedBudget.amount;

		budgets.set(newBudgets);
	}
</script>

<div class="container">
	<Card title="Income" margin="0 0 24px 0">
		<MonthTable
			slot="content"
			title="Income"
			categories={$categories.filter((c) => c.ctype === 'income')}
			transactions={$transactions}
			budgets={$budgets}
			{selectedCategory}
			{selectCategory}
			{setBudget}
		/>
	</Card>
	<Card title="Expense">
		<MonthTable
			slot="content"
			title="Expense"
			categories={$categories.filter((c) => c.ctype === 'expense')}
			transactions={$transactions}
			budgets={$budgets}
			{selectedCategory}
			{selectCategory}
			{setBudget}
		/>
	</Card>
	<Modal title="Set Budget" bind:isOpen={isBudgetDialogOpen}>
		<BudgetForm
			slot="content"
			categoryId={selectedCategory.id}
			{handleBudget}
		/>
	</Modal>
</div>

<style>
	.container {
		width: 100%;
		display: flex;
		flex-direction: column;
	}
</style>

// src/react/views/monthView/monthTableContainer/MonthTableContainer.tsx
import { Button } from '@material-ui/core'
import React, { useState } from 'react'
import { useDispatch } from 'react-redux'
import { saveBudgets } from '../../../slices/budgets'
import { Category, NewBudget, Transaction } from '../../../../shared/types'
import SetBudgetsDialog, { UnprocessedBudgets } from './SetBudgetsDialog'
import MonthTable from './MonthTable'
import { BudgetsByCategory } from '../../../types'

interface Props {
  selectCategory: (category: Category) => void;
  selectedCategory: Category;
  selectedDate: string;
  categories: Category[];
  transactions: Transaction[];
  budgets: BudgetsByCategory;
}

const MonthTableContainer = ({ selectCategory, selectedCategory, selectedDate, categories, transactions, budgets }: Props): JSX.Element => {
  const [isBudgetDialogOpen, setIsBudgetDialogOpen] = useState(false);

  const dispatch = useDispatch();

  const openBudgetDialog = () => setIsBudgetDialogOpen(true);
  
    const closeDialogs = () => {
      setIsBudgetDialogOpen(false);
  }

  const setBudgets = (budgets: UnprocessedBudgets) => {
    const processedBudgets: NewBudget[] = [];

    for (const categoryId in budgets) {
      const budget: NewBudget = {
        amount: Number(budgets[categoryId]),
        startDate: selectedDate,
        categoryId: Number(categoryId),
      }

      if(budget.amount > 0) processedBudgets.push(budget);
    }

    dispatch(saveBudgets(processedBudgets));
    closeDialogs();
  }

  return (
    <>
      <MonthTable
        title="Income"
        categories={categories.filter(c => c.type === 'income')}
        selectedCategory={selectedCategory}
        transactions={transactions}
        budgets={budgets}
        selectCategory={selectCategory}
      />
      <MonthTable
        title="Expense"
        categories={categories.filter(c => c.type === 'expense')}
        selectedCategory={selectedCategory}
        transactions={transactions}
        budgets={budgets}
        selectCategory={selectCategory}
      />
      <Button onClick={openBudgetDialog}>Set Budgets</Button>
      <SetBudgetsDialog
        isOpen={isBudgetDialogOpen}
        incomeCategories={categories.filter(c => c.type === 'income')}
        expenseCategories={categories.filter(c => c.type === 'expense')}
        budgets={budgets}
        handleClose={closeDialogs}
        handleSetBudgets={setBudgets}
      />
    </>
  )
}

export default MonthTableContainer
