// src/routes/month/RatioBar.svelte
<script lang="ts">
  import { roundToDecimals } from "../../utils/round";
  
  export let ratio: number; 
</script>

{#if !isFinite(ratio) || ratio == 0}
  <div style="background-color: #eeeeee33">0%</div>
{:else if ratio > 100}
  <div style="background: linear-gradient(to right, #FF5D7399 {ratio-100}%, #eeeeee33 {ratio-100}%)">
    {roundToDecimals(ratio, 0)}%
  </div>
{:else if ratio > 0}
  <div style="background: linear-gradient(to right, #66B088bb {ratio}%, #eeeeee33 {ratio}%)">
    {roundToDecimals(ratio, 0)}%
  </div>
{/if}

<style>
div {
  text-align: center;
}
</style>

// src/react/views/monthView/monthTableContainer/RatioBar.tsx
import { makeStyles } from '@material-ui/core'
import React from 'react'
import { roundToDecimals } from '../../../utils/round';

const useStyles = makeStyles({
  root: {
    textAlign: 'center'
  },
})

interface Props {
  ratio: number;
}

const RatioBar = ({ ratio }: Props) => {
  const classes = useStyles();

  if (!isFinite(ratio)) return (
    <div className={classes.root} style={{ backgroundColor: '#eeeeee33' }}>
      0%
    </div>
  )

  if (ratio > 100) return (
    <div className={classes.root} style={{ background: `linear-gradient(to right, #FF5D7399 ${ratio-100}%, #eeeeee33 ${ratio-100}%)`}}>
      {roundToDecimals(ratio, 0)}%
    </div>
  )

  return (
    <div className={classes.root} style={{ background: `linear-gradient(to right, #66B088bb ${ratio}%, #eeeeee33 ${ratio}%)`}}>
      {roundToDecimals(ratio, 0)}%
    </div>
  )
}

export default RatioBar
