// src/react/views/recurringView/RecurringExpenseCard.tsx
import { Grid, IconButton, makeStyles, Paper, Typography } from '@material-ui/core'
import React from 'react'
import { RecurringExpense } from '../../../shared/types'
import CustomIcon from '../../components/CustomIcon'

const useStyles = makeStyles(theme => ({
  paper: {
    minWidth: '300px',
    maxWidth: '640px',
    height: '100px',
    padding: '16px',
    marginBottom: '20px',
    ['@media (min-width:960px)']: { // eslint-disable-line no-useless-computed-key
      height: '120px'
    },
    ['@media (min-width:1162px)']: { // eslint-disable-line no-useless-computed-key
      height: '100px'
    }
  },
  editButton: {
    color: theme.palette.text.secondary,
  },
  alarm: {
    marginTop: '10px',
    display: 'flex',
    alignItems: 'flex-end'
  },
  alarmText: {
    marginLeft: '5px',
  }
}))

interface Props {
  expense: RecurringExpense;
  editExpense: (expense: RecurringExpense) => void;
  removeExpense: (expense: RecurringExpense) => void;
}

const RecurringExpenseCard = ({ expense, editExpense, removeExpense }: Props) => {
  const classes = useStyles();
  
  return (
    <Paper key={expense.name} className={classes.paper} elevation={6}>
      <Grid container direction="row">
        <Grid item container xs={3} md={4} direction="column" justify="space-between">
          <Typography variant="h5">{expense.name}</Typography>
          <div className={classes.alarm}>
            <CustomIcon icon="alarm" />
            <Typography className={classes.alarmText} variant="caption">{expense.notifyDaysBefore}</Typography>
          </div>
        </Grid>
        <Grid item xs={6} md={5} container direction="column" justify="space-around">
          <Typography variant="body1">{expense.amount} {expense.recurs}</Typography>
          { expense.recurs === 'monthly' && <Typography variant="body1">Occurs on {expense.day}. of each month</Typography>}
          { expense.recurs === 'yearly' && <Typography variant="body1">Occurs on {expense.day}.{expense.month}. of each year</Typography>}
        </Grid>
        <Grid item xs={3} container justify="flex-end">
          <IconButton
            className={classes.editButton}
            onClick={() => editExpense(expense)} 
          >
            <CustomIcon icon="edit" />
          </IconButton>
          <IconButton 
            color="secondary"
            onClick={() => removeExpense(expense)}
          >
            <CustomIcon icon="delete" />
          </IconButton>
        </Grid>
      </Grid>
    </Paper>
  )
}

export default RecurringExpenseCard

// src/lib/recurring/RecurringExpenseCard.svelte
<script lang="ts">
	import type { RecurringExpense } from '../../types';
	import Card from '$lib/components/Card.svelte';
	import SvgIcon from '$lib/components/SvgIcon.svelte';
	import IconButton from '$lib/components/IconButton.svelte';

	export let expense: RecurringExpense;
	export let editExpense: (expense: RecurringExpense) => void;
	export let removeExpense: (expense: RecurringExpense) => void;
</script>

<Card margin="0 0 16px 0" padding="8px 24px">
	<div slot="content" class="container">
		<div class="col1">
			<h2>{expense.name}</h2>
			<div class="alarm">
				<SvgIcon icon="alarm" size={24} />
				<div class="alarm-text">{expense.notifyDaysBefore}</div>
			</div>
		</div>
		<div class="col2">
			<div>{expense.amount} {expense.recurs}</div>
			{#if expense.recurs === 'monthly'}
				<div>Occurs on {expense.day}. of each month</div>
			{/if}
			{#if expense.recurs === 'yearly'}
				<div>Occurs on {expense.day}.{expense.month} of each year</div>
			{/if}
		</div>
		<div class="col3">
			<IconButton icon="edit" size={24} color="var(--text-secondary)" on:click={() => editExpense(expense)} />
			<IconButton icon="delete" size={24} color="var(--accent-color)" on:click={() => removeExpense(expense)} />
		</div>
	</div>
</Card>

<style>
	.container {
		display: flex;
		width: 100%;
	}
	.col1,
	.col2,
	.col3 {
		display: flex;
		flex-direction: column;
	}
	.col1 {
		width: 33%;
		justify-content: space-around;
	}
	.col1 h2 {
		font-size: 1.4rem;
		margin: 0;
	}
	.alarm {
		display: flex;
		align-items: center;
	}
	.alarm-text {
		margin-left: 5px;
		font-size: 0.9rem;
	}
	.col2 {
		width: 57%;
		justify-content: space-around;
		font-size: 1.1rem;
	}
	.col3 {
		width: 10%;
	}
</style>
