// src/lib/settings/CategoryTable.svelte
<script lang="ts">
	import DropDown from '$lib/components/DropDown.svelte';
	import DropDownItem from '$lib/components/DropDownItem.svelte';
	import type { Category } from '../../types';

	export let categories: Category[];
	export let selectedCategory: Category;
	export let selectCategory: (category: Category) => void;
	export let editCategory: (category: Category) => void;
	export let startCategoryRemoval: (category: Category) => void;
</script>

<table>
	<tr class="header">
		<th>Category</th>
		<th>Type</th>
		<th>Created</th>
		<th>Removed</th>
		<th>Actions</th>
	</tr>
	{#each categories as category}
		<tr class:selected={selectedCategory?.name == category.name} on:click={() => selectCategory(category)}>
			<td>{category.name}</td>
			<td>{category.ctype.charAt(0).toUpperCase() + category.ctype.substr(1)}</td>
			<td>{category.created}</td>
			<td>{category.removed ? category.removed : '-'}</td>
			<td>
				<DropDown text="...">
					<DropDownItem text="Rename" on:click={() => editCategory(selectedCategory)}/>
					<DropDownItem text="Remove" on:click={() => startCategoryRemoval(selectedCategory)} />
				</DropDown>
			</td>
		</tr>
	{/each}
</table>

// src/react/views/SettingsView/CategorySettingsContainer/CategoryTable.tsx
import { makeStyles, Card, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TableSortLabel, Button } from '@material-ui/core'
import React from 'react'
import { Category } from '../../../../shared/types'

const useStyles = makeStyles({
  headerCell: {
    width: '28%',
  },
  valueCell: {
    width: '24%',
  }
})

interface Props {
  className: string;
  categories: Category[];
  selectedCategory: Category | null;
  selectCategory: (category: Category) => void;
}

const CategoryTable = ({ className, categories, selectedCategory, selectCategory }: Props): JSX.Element | null => {
  const classes = useStyles();

  return (
    <TableContainer
      className={className}
      component={Card}
    >
      <Table>
        <TableHead>
          <TableRow>
            <TableCell className={classes.headerCell}>Category</TableCell>
            <TableCell className={classes.valueCell}><TableSortLabel>Type</TableSortLabel></TableCell>
            <TableCell className={classes.valueCell}>Created</TableCell>
            <TableCell className={classes.valueCell}>Removed</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {categories.map(category => (
            <TableRow
                key={category.name}
                hover 
                selected={selectedCategory === category}
                onClick={() => selectCategory(category)}
              >
              <TableCell>{category.name}</TableCell>
              <TableCell>{category.type[0].toUpperCase() + category.type.substr(1)}</TableCell>
              <TableCell>{category.created}</TableCell>
              <TableCell>{category.removed || '-'}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  )
}

export default CategoryTable;
