// src/lib/month/MonthTable.svelte
<script lang="ts">
	import DropDown from '$lib/components/DropDown.svelte';
	import DropDownItem from '$lib/components/DropDownItem.svelte';
	import RatioBar from './RatioBar.svelte';
	import type { Category, Transaction, BudgetsByCategory } from '../../types';
	import { roundToDecimals } from '../../utils/round';
	import { sumOfTransactionsInCategory, sumOfTransactionsInCategories } from '../../utils/sums';

	export let title: 'Income' | 'Expense';
	export let categories: Category[];
	export let selectedCategory: Category;
	export let transactions: Transaction[];
	export let budgets: BudgetsByCategory;
	export let selectCategory: (category: Category) => void;
	export let setBudget: () => void;

	let sumOfTransactions: { [key: string]: string } = {};

	$: {
		categories.forEach(c => {
			sumOfTransactions[c.name] = sumOfTransactionsInCategory(c, transactions);
		})
	}
</script>

<table>
	<tr class="header">
		<th style="width: 25%">Category</th>
		<th style="width: 21%">Budgeted</th>
		<th style="width: 21%">Real</th>
		<th style="width: 21%">Ratio</th>
		<th style="width: 12%; text-align: center;">Actions</th>
	</tr>
	{#each categories as category}
		<tr class:selected={selectedCategory?.name == category.name} on:click={() => selectCategory(category)}>
			<td>{category.name}</td>
			<td>{roundToDecimals(budgets[category.id], 2)}</td>
			<td>{sumOfTransactions[category.name]}</td>
			<td><RatioBar ratio={Number(sumOfTransactions[category.name]) / budgets[category.id] * 100} /></td>
			<td class="table-action">
				<DropDown text="...">
					<DropDownItem text="Set Budget" on:click={() => setBudget()} />
				</DropDown>
			</td>
		</tr>
	{/each}
	<tr>
		<td>Total</td>
		<td>
			{title === 'Income' ? roundToDecimals(budgets['income'], 2) : roundToDecimals(budgets['expense'], 2)}
		</td>
		<td>{sumOfTransactionsInCategories(categories, transactions)}</td>
		<td></td>
		<td></td>
	</tr>
</table>

// src/react/views/MonthView/MonthTable.tsx
import { Card, makeStyles, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@material-ui/core'
import React from 'react'
import { Category, Transaction } from '../../../shared/types'
import { BudgetsByCategory } from '../../types'
import { roundToDecimals } from '../../utils/round'
import { sumOfCategoryTransactions } from './utils'

const useStyles = makeStyles({
  title: {
    marginBottom: '20px'
  },
  headerCell: {
    width: '28%',
  },
  valueCell: {
    width: '24%',
  }
})

interface Props {
  className: string,
  title: string,
  categories: Category[],
  selectedCategory: Category,
  transactions: Transaction[],
  budgets: BudgetsByCategory,
  selectCategory: (category: Category) => void
}

const MonthTable = ({ className, title, categories, selectedCategory, transactions, budgets, selectCategory }: Props): JSX.Element | null => {
  const classes = useStyles();

  return (
    <Card className={className}>
      <Typography variant="h5" className={classes.title}>{title}</Typography>
      <TableContainer>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell className={classes.headerCell}>Category</TableCell>
              <TableCell className={classes.valueCell}>Budgeted</TableCell>
              <TableCell className={classes.valueCell}>Real</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {categories.map(category => (
              <TableRow
                  key={category.name}
                  hover 
                  selected={selectedCategory === category}
                  onClick={() => selectCategory(category)}
                >
                <TableCell>{category.name}</TableCell>
                <TableCell>{roundToDecimals(budgets[category.id], 2)}</TableCell>
                <TableCell>{sumOfCategoryTransactions(category, transactions)}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Card>
  )
}

export default MonthTable;
