// src/react/components/AmountField.tsx
import React, { useState } from 'react'
import { makeStyles } from '@material-ui/core'
import { roundToDecimals } from '../utils/round';

const useStyles = makeStyles(theme => ({
  amountRoot: {
    marginTop: '16px',
    marginBottom: '8px',
    width: '350px',
    position: 'relative',
  },
  amountInput: {
    padding: '6px 0 7px',
    color: 'white',
    backgroundColor: 'transparent',
    outline: 'none',
    border: 'none',
    borderBottom: '2px solid #bbbbbbbb',
    width: '100%',
    fontFamily: theme.typography.fontFamily,
    fontSize: theme.typography.fontSize,
    position: 'relative',
    '&:hover': {
      borderBottom: '2px solid white',
    },
    '&:focus': {
      borderBottom: `2px solid ${theme.palette.primary.main}`
    },
  },
  errorText: {
    color: 'red',
  },
  error: {
    color: 'red',
    borderBottom: '2px solid red',
  },
  amountLabel: {
    fontSize: '1rem',
    position: 'absolute',
    bottom: 5,
    color: theme.palette.text.secondary,
    transition: '200ms',
    transformOrigin: 'top left',
  },
  transformedLabel: {
    transform: 'translate(0, -24px) scale(0.75)',
  },
  focusedLabel: {
    color: theme.palette.primary.main
  },
}))

interface Props {
  name: string;
  label: string;
  defaultValue?: number | string;
  error?: boolean;
  helperText?: React.ReactNode;
  required?: boolean;
}

const AmountField = React.forwardRef<HTMLInputElement, Props>((props, ref) => {
  const [isFocused, setIsFocused] = useState(false);
  const [value, setValue] = useState('');
  
  const classes = useStyles();

  function handleChange (event: React.ChangeEvent<HTMLInputElement>) {
    setValue(event.currentTarget.value);
  }

  function handleFocus (event: React.FocusEvent<HTMLInputElement>) {
    setIsFocused(true);
  }

  function handleBlur (event: React.FocusEvent<HTMLInputElement>) {
    if (value.startsWith('=')) calculateMath(value.substr(1));
    setIsFocused(false);
  }

  function handleKeyPress (event: React.KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'Enter' && value.startsWith('=')) {
      calculateMath(value.substr(1));
    }
  }

  function calculateMath(math: string) {
    const result = roundToDecimals(eval(math), 2);
    setValue(result);
  }

  return (
    <div className={classes.amountRoot}>
      <span
        className={`
          ${classes.amountLabel}
          ${isFocused && classes.focusedLabel} 
          ${(value.length > 0 || props.defaultValue || isFocused && !props.error) && classes.transformedLabel}
          ${props.error && classes.errorText}
        `}
      >
        {props.label}{props.required && ' *'}
      </span>
      <input
        ref={ref}
        className={`${classes.amountInput} ${props.error && classes.error}`}
        name={props.name}
        value={value || props.defaultValue || ''}
        onChange={handleChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onKeyPress={handleKeyPress}
      />
      <span className={classes.errorText}>{props.helperText}</span>
    </div>
  )
})

export default AmountField

// src/lib/components/AmountField.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { roundToDecimals } from '../../utils/round';

	export let label: string;
	export let value: string | number;
	export let helperText = '';
	export let autoFocus = false;

	let inputRef: HTMLInputElement;

	function handleBlur() {
		if (value.toString().length == 0) return;
		value = trim(value);
		value = replaceCommasWithDots(value);
		calculateMath(value);
	}

	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			if (value.toString().length == 0) return;
			value = trim(value);
			value = replaceCommasWithDots(value);
			calculateMath(value);
		}
	}

	function trim(value: string | number) {
		let text = value.toString();
		while (isNaN(Number(text[0]))) text = text.substr(1);
		let length = text.length;
		while (isNaN(Number(text[length - 1]))) {
			text = text.substr(0, length - 1);
			length--;
		}
		return text;
	}

	function replaceCommasWithDots(value: string | number) {
		let text = value.toString();
		while (text.indexOf(',') !== -1) {
			text = text.replace(',', '.');
		}
		return text;
	}

	function calculateMath(input: string | number) {
		const math = input.toString();
		value = roundToDecimals(eval(math), 2);
	}

	onMount(() => {
		if (autoFocus) inputRef.focus();
	});
</script>

<div>
	<span class="label" class:error={helperText}>{label}</span>
	<input
		class:error={helperText.length > 0}
		bind:value
		bind:this={inputRef}
		on:blur={handleBlur}
		on:keydown={handleKeyDown}
	/>
	<span class="helperText">{helperText}</span>
</div>

<style>
	div {
		display: flex;
		flex-direction: column;
	}
	.label {
		color: var(--text-secondary);
		font-size: 0.85rem;
		margin-left: 5px;
	}
	input {
		margin: 8px 0;
		padding: 8px;
		background-color: transparent;
		border: 1px solid var(--text-secondary);
		border-radius: 8px;
		color: var(--text-primary);
	}
	input:hover:not(:focus) {
		padding: 6px;
		border: 3px solid var(--text-secondary);
	}
	input:focus {
		outline: none;
		border: 1px solid var(--primary-main);
	}
	div:focus-within .label {
		color: var(--primary-main);
	}
	.helperText {
		color: var(--accent-color);
		font-size: 0.9rem;
	}
	.error {
		color: var(--accent-color) !important;
		border-color: var(--accent-color) !important;
	}
</style>
